version: 2
jobs:

  one:
    build:
      docker:
        - image: circleci/python:3.7.4
      environment:
        PIPENV_VENV_IN_PROJECT: true
      steps:
        - checkout
        - run: python -m pip install --upgrade pip
        
  two:
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
      steps:
        - checkout
        - run: |
          pip install pytest
          pytest
  workflows:
    version: 2
    one_and_two:
    jobs:
      - one
      - two:
        requires:
          - one
  
    
  
